#!/bin/sh

# Install all needed packages fot systems with apt as their package manager
if command -v apt
then
	sudo apt update && sudo apt upgrade
	sudo apt install -y curl zsh fzf neovim vifm kitty fonts-powerline ripgrep nodejs npm
fi

# Install all needed packages fot systems with apt as their package manager
if command -v dnf
then
	sudo dnf upgrade -y
	sudo dnf install -y curl zsh fzf neovim vifm kitty powerline-fonts ripgrep nodejs npm util-linux-user
fi

# Install oh-my-zsh if itsn't not installed
if [ ! -d ~/.oh-my-zsh ]
then
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	rm ~/.zshrc
fi

# Create all the needed directories for the config files
mkdir -p ~/.config/nvim ~/.config/kitty ~/.config/vifm

# Link all the config files to the correct places
ln -sf $(pwd)/.aliases ~/
ln -sf $(pwd)/.zshrc ~/
ln -sf $(pwd)/.ignore ~/
ln -sf $(pwd)/init.vim ~/.config/nvim/
ln -sf $(pwd)/kitty.conf ~/.config/kitty/
ln -sf $(pwd)/vifmrc ~/.config/vifm/

# Install VimPlug to install all the vim plugins if it's not installed yet
if ! test -f ~/.local/share/nvim/site/autoload/plug.vim
then
	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
