#!/bin/sh

if command -v apt
then
	sudo apt update && sudo apt upgrade
	sudo apt install -y zsh fzf neovim vifm kitty
fi

if ! test -f ~/.zshrc
then
	sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
fi

mkdir -p ~/.config/nvim ~/.config/kitty ~/.config/vifm

ln -sf $(pwd)/.aliases ~/
ln -sf $(pwd)/.zshrc ~/
ln -sf $(pwd)/.ignore ~/
ln -sf $(pwd)/init.vim ~/.config/nvim/
ln -sf $(pwd)/kitty.conf ~/.config/kitty/
ln -sf $(pwd)/vifmrc ~/.config/vifm/
