#!/bin/zsh

# Pathogen install
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# surround install
git clone https://github.com/tpope/vim-surround.git ~/.vim/bundle/surround

# typescript-vim install
git clone https://github.com/leafgarland/typescript-vim.git ~/.vim/bundle/typescript-vim

# vim-js-pretty-template install
git clone https://github.com/Quramy/vim-js-pretty-template.git ~/.vim/bundle/vim-js-pretty-template

# vim-commentray install
git clone git://github.com/tpope/vim-commentary.git ~/.vim/bundle/vim-commentary

# vim-blade install
git clone git://github.com/jwalton512/vim-blade.git ~/.vim/bundle/vim-blade

# vue-syntax install
git clone https://github.com/posva/vim-vue.git ~/.vim/bundle/vim-vue

# vim-ags install
git clone https://github.com/junegunn/fzf.vim.git ~/.vim/bundle/fzf

# NERDTree install
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

# scss syntax install
git clone https://github.com/cakebaker/scss-syntax.vim ~/.vim/bundle/scss-syntax

# react syntax install
git clone https://github.com/mxw/vim-jsx.git ~/.vim/bundle/vim-jsx

# syntastic install
git clone --depth=1 https://github.com/vim-syntastic/syntastic.git ~/.vim/bundle/syntastic

# Signify
git clone git@github.com:mhinz/vim-signify.git ~/.vim/bundle/signify

# editorconfig
git clone https://github.com/editorconfig/editorconfig-vim.git ~/.vim/bundle/editorconfig-vim

# vim-javascript
git clone https://github.com/pangloss/vim-javascript.git ~/.vim/bundle/vim-javascript

# procvim.vim
 git clone https://github.com/Shougo/vimproc.vim.git ~/.vim/bundle/vimproc.vim
 pushd ~/.vim/bundle/vimproc.vim
 make
 popd

# tsuquyomi
git clone https://github.com/Quramy/tsuquyomi.git ~/.vim/bundle/tsuquyomi

# airline
git clone https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/vim-airline
