#!/bin/zsh

# Pathogen install
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# surround install
git clone https://github.com/tpope/vim-surround.git ~/.vim/bundle/surround

# powerline install
git clone https://github.com/powerline/powerline.git ~/.vim/bundle/powerline

# typescript-vim install
git clone https://github.com/leafgarland/typescript-vim.git ~/.vim/bundle/typescript-vim

# vim-js-pretty-template install
git clone https://github.com/Quramy/vim-js-pretty-template.git ~/.vim/bundle/vim-js-pretty-template

# vim-commentray install
git clone git://github.com/tpope/vim-commentary.git ~/.vim/bundle/vim-commentary

# vim-blade install
git clone git://github.com/jwalton512/vim-blade.git ~/.vim/bundle/vim-blade

# vue-syntax install
git clone https://github.com/posva/vim-vue.git ~/.vim/bundle/vim-vue

# vim-ags install
git clone https://github.com/gabesoft/vim-ags.git ~/.vim/bundle/vim-ags

# NERDTree install
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

# scss syntax install
git clone https://github.com/cakebaker/scss-syntax.vim ~/.vim/bundle/scss-syntax

# react syntax install
git clone https://github.com/mxw/vim-jsx.git ~/.vim/bundle/vim-jsx

# ale install
git clone https://github.com/w0rp/ale.git ~/.vim/bundle/ale
