#!/bin/zsh

SOURCE_DIR=/home/lars/Code/dotfiles

ln -sf $SOURCE_DIR/.vimrc ~/
ln -sf $SOURCE_DIR/.jshintrc ~/
ln -sf $SOURCE_DIR/.i3 ~/
ln -sf $SOURCE_DIR/.i3blocks.conf ~/
ln -sf $SOURCE_DIR/.xinitrc ~/
ln -sf $SOURCE_DIR/.Xdefaults ~/
ln -sf $SOURCE_DIR/dunst ~/.config/
ln -sf $SOURCE_DIR/.zshrc ~/
ln -sf $SOURCE_DIR/.zshrc /root/
ln -sf $SOURCE_DIR/.aliases ~/
ln -sf $SOURCE_DIR/.aliases /root/
