#!/bin/sh

mkdir ~/.config

ln -sf .vimrc ~/
ln -sf .i3 ~/
ln -sf .i3blocks.conf ~/
ln -sf .zshrc ~/
ln -sf .aliases ~/
ln -sf .xinitrc ~/
ln -sf dunst ~/.config/
ln -sf termite ~/.config/
ln -sf .ctags ~/
sudo ln -sf .zshrc /root/
sudo ln -sf .aliases /root/
